- hosts: localhost
  name: local
  tasks:
  - name: Create VM
    kubevirt.core.kubevirt_vm:
      state: present
      name: testvm
      namespace: kubevirt-ansible
      labels:
        app: test
      instancetype:
        name: u1.medium
      preference:
        name: fedora
      spec:
        domain:
          devices:
            interfaces:
            - name: default
              masquerade: {}
            - name: secondary-network
              bridge: {}
        networks:
        - name: default
          pod: {}
        - name: secondary-network
          multus:
            networkName: secondary-network
        accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: my-pub-key
            propagationMethod:
              configDrive: {}
        volumes:
        - containerDisk:
            image: quay.io/containerdisks/fedora:latest
          name: containerdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              # The default username is: fedora
          name: cloudinit
      wait: yes
